simple:
  key1: value1
  key2: value2
  key3: 123
complex:
  name: complex-name
  ts: 1234567890
  val: 1.201E+4
  tags:
    t1: tag-value-1
    t2: tag-value-2
    t3: tag-value-3

vec:
  - name: vec-elem-1
    val: value-1
    tags:
      t1: v1-t1
      t2: v1-t2
  - name: vec-elem-2
    val: value-2
    tags:
      t1: v2-t1
      t2: v2-t2
